import { describe, expect, it, beforeEach, afterEach, vi } from "vitest";
import { promises as fs, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { removeWithRetry } from "./helpers/remove-with-retry.js";
import {
	createNamedBackup,
	listAccountSnapshots,
	getNamedBackupsDirectoryPath,
	loadAccounts,
	getBackupMetadata,
	pruneAutoGeneratedSnapshots,
	saveAccounts,
	setStorageBackupEnabled,
	setStoragePathDirect,
	snapshotAccountStorage,
	snapshotAndClearAccounts,
	clearAccounts,
	getRestoreAssessment,
	withAccountAndFlaggedStorageTransaction,
} from "../lib/storage.js";
import {
	__resetSyncHistoryForTests,
	appendSyncHistoryEntry,
	configureSyncHistoryForTests,
} from "../lib/sync-history.js";
import * as syncHistoryModule from "../lib/sync-history.js";

function getRestoreEligibility(value: unknown): { restoreEligible?: boolean; restoreReason?: string } {
	if (value && typeof value === "object" && "restoreEligible" in value) {
		const candidate = value as { restoreEligible?: unknown; restoreReason?: unknown };
		return {
			restoreEligible: typeof candidate.restoreEligible === "boolean" ? candidate.restoreEligible : undefined,
			restoreReason: typeof candidate.restoreReason === "string" ? candidate.restoreReason : undefined,
		};
	}
	return {};
}

function sha256(value: string): string {
	return createHash("sha256").update(value).digest("hex");
}

describe("storage recovery paths", () => {
	let workDir = "";
	let storagePath = "";

	beforeEach(async () => {
		workDir = join(tmpdir(), `codex-storage-recovery-${Date.now()}-${Math.random().toString(36).slice(2)}`);
		storagePath = join(workDir, "openai-codex-accounts.json");
		await fs.mkdir(workDir, { recursive: true });
		configureSyncHistoryForTests(join(workDir, "logs"));
		setStoragePathDirect(storagePath);
		setStorageBackupEnabled(true);
	});

	afterEach(async () => {
		await __resetSyncHistoryForTests();
		configureSyncHistoryForTests(null);
		setStoragePathDirect(null);
		setStorageBackupEnabled(true);
		await removeWithRetry(workDir, { recursive: true, force: true });
	});

	it("aborts snapshotAndClearAccounts when snapshot capture fails", async () => {
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					accountId: "acc-keep",
					accountIdSource: "token",
					email: "keep@example.com",
					refreshToken: "refresh-keep",
					accessToken: "access-keep",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		});

		const originalWriteFile = fs.writeFile.bind(fs);
		const writeFileSpy = vi
			.spyOn(fs, "writeFile")
			.mockImplementation(async (path, data, options) => {
				if (String(path).includes("accounts-reset-local-state-snapshot-")) {
					const error = new Error("snapshot write denied") as NodeJS.ErrnoException;
					error.code = "EACCES";
					throw error;
				}
				return originalWriteFile(path as never, data as never, options as never);
			});

		try {
			await expect(
				snapshotAndClearAccounts("reset-local-state"),
			).rejects.toMatchObject({ code: "EACCES" });

			const persisted = await loadAccounts();
			expect(persisted?.accounts).toHaveLength(1);
			expect(persisted?.accounts[0]?.refreshToken).toBe("refresh-keep");

			const backupsDir = getNamedBackupsDirectoryPath();
			const backupEntries = existsSync(backupsDir)
				? await fs.readdir(backupsDir)
				: [];
			expect(
				backupEntries.some((name) =>
					name.startsWith("accounts-reset-local-state-snapshot-"),
				),
			).toBe(false);
		} finally {
			writeFileSpy.mockRestore();
		}
	});

	it("recovers from WAL journal when primary storage is unreadable", async () => {
		await fs.writeFile(storagePath, "{invalid-json", "utf-8");

		const walPayload = {
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "wal-refresh",
					accountId: "from-wal",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		};
		const walContent = JSON.stringify(walPayload);
		const walEntry = {
			version: 1,
			createdAt: Date.now(),
			path: storagePath,
			checksum: sha256(walContent),
			content: walContent,
		};
		await fs.writeFile(`${storagePath}.wal`, JSON.stringify(walEntry), "utf-8");

		const recovered = await loadAccounts();
		expect(recovered?.accounts).toHaveLength(1);
		expect(recovered?.accounts[0]?.accountId).toBe("from-wal");

		const persisted = JSON.parse(await fs.readFile(storagePath, "utf-8")) as {
			accounts?: Array<{ accountId?: string }>;
		};
		expect(persisted.accounts?.[0]?.accountId).toBe("from-wal");
	});

	it("recovers from backup file when WAL is unavailable", async () => {
		await fs.writeFile(storagePath, "{still-invalid", "utf-8");

		const backupPayload = {
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "backup-refresh",
					accountId: "from-backup",
					addedAt: 2,
					lastUsed: 2,
				},
			],
		};
		await fs.writeFile(`${storagePath}.bak`, JSON.stringify(backupPayload), "utf-8");

		const recovered = await loadAccounts();
		expect(recovered?.accounts).toHaveLength(1);
		expect(recovered?.accounts[0]?.accountId).toBe("from-backup");

		const persisted = JSON.parse(await fs.readFile(storagePath, "utf-8")) as {
			accounts?: Array<{ accountId?: string }>;
		};
		expect(persisted.accounts?.[0]?.accountId).toBe("from-backup");
	});

	it("falls back to historical backup snapshots when the latest backup is unreadable", async () => {
		await fs.writeFile(storagePath, "{broken-primary", "utf-8");
		await fs.writeFile(`${storagePath}.bak`, "{broken-latest-backup", "utf-8");

		const historicalBackupPayload = {
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "historical-refresh",
					accountId: "from-backup-history",
					addedAt: 4,
					lastUsed: 4,
				},
			],
		};
		await fs.writeFile(`${storagePath}.bak.1`, JSON.stringify(historicalBackupPayload), "utf-8");

		const recovered = await loadAccounts();
		expect(recovered?.accounts).toHaveLength(1);
		expect(recovered?.accounts[0]?.accountId).toBe("from-backup-history");

		const persisted = JSON.parse(await fs.readFile(storagePath, "utf-8")) as {
			accounts?: Array<{ accountId?: string }>;
		};
		expect(persisted.accounts?.[0]?.accountId).toBe("from-backup-history");
	});

	it("falls back to .bak.2 when newer backups are unreadable", async () => {
		await fs.writeFile(storagePath, "{broken-primary", "utf-8");
		await fs.writeFile(`${storagePath}.bak`, "{broken-bak", "utf-8");
		await fs.writeFile(`${storagePath}.bak.1`, "{broken-bak-1", "utf-8");

		const oldestBackupPayload = {
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "deep-refresh",
					accountId: "from-backup-2",
					addedAt: 5,
					lastUsed: 5,
				},
			],
		};
		await fs.writeFile(`${storagePath}.bak.2`, JSON.stringify(oldestBackupPayload), "utf-8");

		const recovered = await loadAccounts();
		expect(recovered?.accounts).toHaveLength(1);
		expect(recovered?.accounts[0]?.accountId).toBe("from-backup-2");

		const persisted = JSON.parse(await fs.readFile(storagePath, "utf-8")) as {
			accounts?: Array<{ accountId?: string }>;
		};
		expect(persisted.accounts?.[0]?.accountId).toBe("from-backup-2");
	});

	it("recovers from discovered non-standard backup artifact when primary file is missing", async () => {
		const discoveredBackupPath = `${storagePath}.manual-before-dedupe-2026-03-03T00-25-19-753Z`;
		await fs.writeFile(
			discoveredBackupPath,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [
					{
						refreshToken: "manual-refresh",
						accountId: "from-discovered-backup",
						addedAt: 6,
						lastUsed: 6,
					},
				],
			}),
			"utf-8",
		);

		const originalHome = process.env.HOME;
		const originalUserProfile = process.env.USERPROFILE;
		try {
			process.env.HOME = workDir;
			process.env.USERPROFILE = workDir;

			const recovered = await loadAccounts();
			expect(recovered?.accounts).toHaveLength(1);
			expect(recovered?.accounts[0]?.accountId).toBe("from-discovered-backup");

			const persisted = JSON.parse(await fs.readFile(storagePath, "utf-8")) as {
				accounts?: Array<{ accountId?: string }>;
			};
			expect(persisted.accounts?.[0]?.accountId).toBe("from-discovered-backup");
		} finally {
			if (originalHome === undefined) delete process.env.HOME;
			else process.env.HOME = originalHome;
			if (originalUserProfile === undefined) delete process.env.USERPROFILE;
			else process.env.USERPROFILE = originalUserProfile;
		}
	});

	it("auto-promotes backup when primary storage matches synthetic fixture pattern", async () => {
		await fs.writeFile(
			storagePath,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [
					{
						email: "account1@example.com",
						refreshToken: "fake_refresh_token_1",
						accountId: "acc_1",
						addedAt: 1,
						lastUsed: 1,
					},
					{
						email: "account2@example.com",
						refreshToken: "fake_refresh_token_2",
						accountId: "acc_2",
						addedAt: 1,
						lastUsed: 1,
					},
				],
			}),
			"utf-8",
		);
		await fs.writeFile(
			`${storagePath}.manual-before-dedupe-2026-03-03T00-25-19-753Z`,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [
					{
						email: "realuser@gmail.com",
						refreshToken: "real-refresh-token",
						accountId: "real-account",
						addedAt: 2,
						lastUsed: 2,
					},
				],
			}),
			"utf-8",
		);

		const recovered = await loadAccounts();
		expect(recovered?.accounts).toHaveLength(1);
		expect(recovered?.accounts[0]?.email).toBe("realuser@gmail.com");

		const persisted = JSON.parse(await fs.readFile(storagePath, "utf-8")) as {
			accounts?: Array<{ email?: string }>;
		};
		expect(persisted.accounts?.[0]?.email).toBe("realuser@gmail.com");
	});

	it("auto-promotes backup when synthetic fixture accounts are missing accountId fields", async () => {
		await fs.writeFile(
			storagePath,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [
					{
						email: "account1@example.com",
						refreshToken: "fake_refresh_token_1_for_testing_only",
						addedAt: 1,
						lastUsed: 1,
					},
					{
						email: "account2@example.com",
						refreshToken: "fake_refresh_token_2_for_testing_only",
						addedAt: 1,
						lastUsed: 1,
					},
				],
			}),
			"utf-8",
		);
		await fs.writeFile(
			`${storagePath}.manual-pre-recovery-test-latest`,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [
					{
						email: "realuser2@gmail.com",
						refreshToken: "real-refresh-token-2",
						accountId: "real-account-2",
						addedAt: 2,
						lastUsed: 2,
					},
				],
			}),
			"utf-8",
		);

		const recovered = await loadAccounts();
		expect(recovered?.accounts).toHaveLength(1);
		expect(recovered?.accounts[0]?.email).toBe("realuser2@gmail.com");

		const persisted = JSON.parse(await fs.readFile(storagePath, "utf-8")) as {
			accounts?: Array<{ email?: string }>;
		};
		expect(persisted.accounts?.[0]?.email).toBe("realuser2@gmail.com");
	});

	it("rejects saving synthetic fixture payload over real account storage", async () => {
		await fs.writeFile(
			storagePath,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [
					{
						email: "realuser@gmail.com",
						refreshToken: "real-refresh-token",
						accountId: "real-account",
						addedAt: 10,
						lastUsed: 10,
					},
				],
			}),
			"utf-8",
		);

		await expect(
			saveAccounts({
				version: 3,
				activeIndex: 0,
				activeIndexByFamily: {},
				accounts: [
					{
						email: "account1@example.com",
						refreshToken: "fake_refresh_token_1",
						accountId: "acc_1",
						addedAt: 11,
						lastUsed: 11,
					},
				],
			}),
		).rejects.toThrow("Refusing to overwrite non-synthetic account storage");

		const persisted = JSON.parse(await fs.readFile(storagePath, "utf-8")) as {
			accounts?: Array<{ email?: string }>;
		};
		expect(persisted.accounts?.[0]?.email).toBe("realuser@gmail.com");
	});

	it("surfaces restore eligibility when account pool is missing", async () => {
		await fs.rm(storagePath, { force: true });

		const recovered = await loadAccounts();
		const eligibility = getRestoreEligibility(recovered);

		expect(eligibility.restoreEligible).toBe(true);
		expect(eligibility.restoreReason).toBe("missing-storage");
	});

	it("surfaces restore eligibility when account pool is empty", async () => {
		await fs.writeFile(
			storagePath,
			JSON.stringify({ version: 3, activeIndex: 0, accounts: [] }),
			"utf-8",
		);

		const recovered = await loadAccounts();
		const eligibility = getRestoreEligibility(recovered);

		expect(eligibility.restoreEligible).toBe(true);
		expect(eligibility.restoreReason).toBe("empty-storage");
	});

	it("suppresses restore eligibility after intentional reset but flags unexpected empty state", async () => {
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "token-reset",
					accountId: "reset-account",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		});

		await clearAccounts();
		const afterIntentionalReset = await loadAccounts();
		const intentionalEligibility = getRestoreEligibility(afterIntentionalReset);
		expect(intentionalEligibility.restoreEligible).toBe(false);

		await saveAccounts({ version: 3, activeIndex: 0, accounts: [] });
		const afterAccidentalEmpty = await loadAccounts();
		const accidentalEligibility = getRestoreEligibility(afterAccidentalEmpty);
		expect(accidentalEligibility.restoreEligible).toBe(true);
	});

	it("assesses restore state with latest snapshot metadata", async () => {
		const backupPayload = {
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "backup-refresh",
					accountId: "from-backup",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		};
		await fs.writeFile(`${storagePath}.bak`, JSON.stringify(backupPayload), "utf-8");

		const assessment = await getRestoreAssessment();

		expect(assessment.restoreEligible).toBe(true);
		expect(assessment.restoreReason).toBe("missing-storage");
		expect(assessment.latestSnapshot?.path).toBe(`${storagePath}.bak`);
		expect(assessment.backupMetadata.accounts.latestValidPath).toBe(`${storagePath}.bak`);
	});

	it("ignores Codex CLI mirror files during restore assessment", async () => {
		const codexCliAccountsPath = join(workDir, "accounts.json");
		const codexCliAuthPath = join(workDir, "auth.json");
		await fs.writeFile(
			codexCliAccountsPath,
			JSON.stringify({
				activeAccountId: "mirror-account",
				accounts: [
					{
						accountId: "mirror-account",
						email: "mirror@example.com",
						auth: {
							tokens: {
								access_token: "mirror-access",
								refresh_token: "mirror-refresh",
							},
						},
					},
				],
			}),
			"utf-8",
		);
		await fs.writeFile(
			codexCliAuthPath,
			JSON.stringify({
				auth_mode: "chatgpt",
				tokens: {
					access_token: "mirror-access",
					refresh_token: "mirror-refresh",
					account_id: "mirror-account",
				},
			}),
			"utf-8",
		);

		const recovered = await loadAccounts();
		const eligibility = getRestoreEligibility(recovered);
		expect(recovered?.accounts).toHaveLength(0);
		expect(eligibility.restoreEligible).toBe(true);
		expect(eligibility.restoreReason).toBe("missing-storage");

		const assessment = await getRestoreAssessment();
		expect(assessment.restoreEligible).toBe(true);
		expect(assessment.restoreReason).toBe("missing-storage");
		expect(assessment.latestSnapshot).toBeUndefined();
		expect(assessment.backupMetadata.accounts.latestValidPath).toBeUndefined();
		expect(
			assessment.backupMetadata.accounts.snapshots.some(
				(snapshot) => snapshot.path === codexCliAccountsPath || snapshot.path === codexCliAuthPath,
			),
		).toBe(false);
	});

	it("returns restore eligibility and snapshot when storage is empty", async () => {
		await fs.writeFile(
			storagePath,
			JSON.stringify({ version: 3, activeIndex: 0, accounts: [] }),
			"utf-8",
		);

		const assessment = await getRestoreAssessment();

		expect(assessment.restoreEligible).toBe(true);
		expect(assessment.restoreReason).toBe("empty-storage");
		expect(assessment.latestSnapshot?.path).toBe(storagePath);
	});

	it("suppresses restore once after intentional reset marker", async () => {
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "token-reset",
					accountId: "reset-account",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		});

		await clearAccounts();

		const suppressed = await getRestoreAssessment();
		expect(suppressed.restoreEligible).toBe(false);
		expect(suppressed.restoreReason).toBe("intentional-reset");

		await saveAccounts({ version: 3, activeIndex: 0, accounts: [] });

		const eligibleAfterReset = await getRestoreAssessment();
		expect(eligibleAfterReset.restoreEligible).toBe(true);
		expect(eligibleAfterReset.restoreReason).toBe("empty-storage");
	});

	it("does not revive WAL contents after reset assessment runs before load", async () => {
		const walPayload = {
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "stale-refresh",
					accountId: "stale-account",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		};
		const walContent = JSON.stringify(walPayload);
		const walEntry = {
			version: 1,
			createdAt: Date.now(),
			path: storagePath,
			checksum: sha256(walContent),
			content: walContent,
		};

		await saveAccounts(walPayload);
		await clearAccounts();
		await fs.writeFile(`${storagePath}.wal`, JSON.stringify(walEntry), "utf-8");

		const assessment = await getRestoreAssessment();
		expect(assessment.restoreEligible).toBe(false);
		expect(assessment.restoreReason).toBe("intentional-reset");

		const reloaded = await loadAccounts();
		expect(reloaded?.accounts).toHaveLength(0);
		expect(getRestoreEligibility(reloaded).restoreReason).toBe("intentional-reset");
	});

	it("suppresses WAL recovery when a reset marker appears while the WAL is being read", async () => {
		const walPayload = {
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "racing-refresh",
					accountId: "racing-account",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		};
		const walContent = JSON.stringify(walPayload);
		const walEntry = {
			version: 1,
			createdAt: Date.now(),
			path: storagePath,
			checksum: sha256(walContent),
			content: walContent,
		};

		await fs.writeFile(`${storagePath}.wal`, JSON.stringify(walEntry), "utf-8");

		const originalReadFile = fs.readFile.bind(fs);
		const originalWriteFile = fs.writeFile.bind(fs);
		const readSpy = vi.spyOn(fs, "readFile").mockImplementation(async (...args) => {
			const [targetPath] = args;
			if (targetPath === `${storagePath}.wal`) {
				await originalWriteFile(
					`${storagePath}.reset-intent`,
					JSON.stringify({ version: 1, createdAt: Date.now() }),
					"utf-8",
				);
			}
			return originalReadFile(...args);
		});

		try {
			const reloaded = await loadAccounts();
			expect(reloaded?.accounts).toHaveLength(0);
			expect(getRestoreEligibility(reloaded).restoreReason).toBe("intentional-reset");
		} finally {
			readSpy.mockRestore();
		}
	});

	it("excludes reset markers from discovered backup metadata", async () => {
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "marker-refresh",
					accountId: "marker-account",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		});

		await clearAccounts();

		const metadata = await getBackupMetadata();
		expect(
			metadata.accounts.snapshots.some((snapshot) =>
				snapshot.path.endsWith(".reset-intent"),
			),
		).toBe(false);
	});

	it("cleans up only stale staged backup artifacts during load", async () => {
		await fs.writeFile(
			storagePath,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [{ refreshToken: "primary-refresh", accountId: "primary", addedAt: 6, lastUsed: 6 }],
			}),
			"utf-8",
		);

		const staleArtifacts = [
			`${storagePath}.bak.rotate.12345.abc123.latest.tmp`,
			`${storagePath}.bak.1.rotate.12345.abc123.slot-1.tmp`,
			`${storagePath}.bak.2.rotate.12345.abc123.slot-2.tmp`,
		];
		for (const staleArtifactPath of staleArtifacts) {
			await fs.writeFile(staleArtifactPath, "stale", "utf-8");
			await fs.utimes(staleArtifactPath, new Date(0), new Date(0));
			expect(existsSync(staleArtifactPath)).toBe(true);
		}
		const freshArtifactPath = `${storagePath}.bak.rotate.54321.fresh.latest.tmp`;
		await fs.writeFile(freshArtifactPath, "fresh", "utf-8");
		expect(existsSync(freshArtifactPath)).toBe(true);
		const unrelatedArtifactPath = `${storagePath}.rotate.12345.abc123.latest.tmp`;
		await fs.writeFile(unrelatedArtifactPath, "keep", "utf-8");
		expect(existsSync(unrelatedArtifactPath)).toBe(true);

		const recovered = await loadAccounts();
		expect(recovered?.accounts).toHaveLength(1);
		expect(recovered?.accounts[0]?.accountId).toBe("primary");

		for (const staleArtifactPath of staleArtifacts) {
			expect(existsSync(staleArtifactPath)).toBe(false);
		}
		expect(existsSync(freshArtifactPath)).toBe(true);
		expect(existsSync(unrelatedArtifactPath)).toBe(true);
	});

	it("does not use backup recovery when backups are disabled", async () => {
		setStorageBackupEnabled(false);
		await fs.writeFile(storagePath, "{broken-primary", "utf-8");
		await fs.writeFile(
			`${storagePath}.bak`,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [{ refreshToken: "backup-refresh", accountId: "disabled-backup", addedAt: 3, lastUsed: 3 }],
			}),
			"utf-8",
		);

		const recovered = await loadAccounts();
		expect(recovered).toBeNull();
	});

	it("exposes snapshot metadata and ignores cache-like artifacts", async () => {
		await fs.writeFile(storagePath, "{invalid-json", "utf-8");

		const walPayload = {
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "wal-refresh-meta",
					accountId: "wal-account",
					addedAt: 10,
					lastUsed: 10,
				},
			],
		};
		const walContent = JSON.stringify(walPayload);
		const walEntry = {
			version: 1,
			createdAt: Date.now(),
			path: storagePath,
			checksum: sha256(walContent),
			content: walContent,
		};
		await fs.writeFile(`${storagePath}.wal`, JSON.stringify(walEntry), "utf-8");

		await fs.writeFile(
			`${storagePath}.bak`,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [
					{
						refreshToken: "bak-refresh-meta",
						accountId: "bak-account",
						addedAt: 5,
						lastUsed: 5,
					},
				],
			}),
			"utf-8",
		);

		await fs.writeFile(`${storagePath}.cache`, "noise", "utf-8");
		const cacheMtime = new Date(Date.now() - 5_000);
		await fs.utimes(`${storagePath}.cache`, cacheMtime, cacheMtime);
		await fs.writeFile(
			`${storagePath}.manual-meta-checkpoint`,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [
					{
						refreshToken: "manual-refresh-meta",
						accountId: "manual-account",
						addedAt: 7,
						lastUsed: 7,
					},
				],
			}),
			"utf-8",
		);
		const manualCheckpointMtime = new Date(Date.now() + 5_000);
		await fs.utimes(
			`${storagePath}.manual-meta-checkpoint`,
			manualCheckpointMtime,
			manualCheckpointMtime,
		);

		const metadata = await getBackupMetadata();
		const accountSnapshots = metadata.accounts.snapshots;
		const cacheEntries = accountSnapshots.filter((snapshot) => snapshot.path.endsWith(".cache"));
		expect(cacheEntries).toHaveLength(0);
		expect(metadata.accounts.latestValidPath).toBe(
			`${storagePath}.manual-meta-checkpoint`,
		);
		const discovered = accountSnapshots.find((snapshot) => snapshot.path.endsWith("manual-meta-checkpoint"));
		expect(discovered?.kind).toBe("accounts-discovered-backup");
		expect(discovered?.valid).toBe(true);
		expect(discovered?.accountCount).toBe(1);
		expect(metadata.accounts.snapshotCount).toBeGreaterThanOrEqual(4);
	});

	it("prefers the newest valid discovered snapshot in backup metadata", async () => {
		const olderManualPath = `${storagePath}.manual-older`;
		const newerManualPath = `${storagePath}.manual-newer`;

		await fs.writeFile(
			olderManualPath,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [{ refreshToken: "older-refresh", accountId: "older", addedAt: 1, lastUsed: 1 }],
			}),
			"utf-8",
		);
		await fs.writeFile(
			newerManualPath,
			JSON.stringify({
				version: 3,
				activeIndex: 0,
				accounts: [{ refreshToken: "newer-refresh", accountId: "newer", addedAt: 2, lastUsed: 2 }],
			}),
			"utf-8",
		);
		const baseMtimeMs = Date.now() - 60_000;
		const olderManualMtime = new Date(baseMtimeMs);
		const newerManualMtime = new Date(baseMtimeMs + 10_000);
		await fs.utimes(olderManualPath, olderManualMtime, olderManualMtime);
		await fs.utimes(newerManualPath, newerManualMtime, newerManualMtime);

		const metadata = await getBackupMetadata();
		expect(metadata.accounts.latestValidPath).toBe(newerManualPath);
	});

	it("prunes older auto snapshots while keeping the latest per reason and manual backups", async () => {
		const backupsDir = getNamedBackupsDirectoryPath();
		await fs.mkdir(backupsDir, { recursive: true });
		const payload = {
			version: 3,
			activeIndex: 0,
			accounts: [{ refreshToken: "rt-a" }],
		};
		const olderName =
			"accounts-codex-cli-sync-snapshot-2026-03-10_00-00-00_000";
		const olderPath = join(backupsDir, `${olderName}.json`);
		const newerName =
			"accounts-codex-cli-sync-snapshot-2026-03-12_00-00-00_000";
		const newerPath = join(backupsDir, `${newerName}.json`);
		const manualPath = join(backupsDir, "manual-checkpoint.json");
		await fs.writeFile(newerPath, JSON.stringify(payload), "utf-8");
		await fs.writeFile(olderPath, JSON.stringify(payload), "utf-8");
		await fs.writeFile(manualPath, JSON.stringify(payload), "utf-8");

		const result = await pruneAutoGeneratedSnapshots({
			keepLatestPerReason: 1,
		});
		expect(result.pruned.map((entry) => entry.name)).toContain(olderName);
		expect(result.kept.map((entry) => entry.name)).toContain(newerName);
		expect(existsSync(olderPath)).toBe(false);
		expect(existsSync(newerPath)).toBe(true);
		expect(existsSync(manualPath)).toBe(true);
	});

	it("does not prune manual backups that only look like auto snapshots", async () => {
		const backupsDir = getNamedBackupsDirectoryPath();
		await fs.mkdir(backupsDir, { recursive: true });
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [{ refreshToken: "rt-a" }],
		});

		const storage = await loadAccounts();
		if (!storage) {
			throw new Error("expected storage");
		}

		const manualBackup = await createNamedBackup(
			"accounts-delete-account-snapshot-2026-03-10_00-00-00_000",
			{ storage },
		);
		const snapshotTimes = [
			Date.UTC(2026, 2, 11, 0, 0, 0, 0),
			Date.UTC(2026, 2, 12, 0, 0, 0, 0),
			Date.UTC(2026, 2, 13, 0, 0, 0, 0),
		];

		for (const now of snapshotTimes) {
			await snapshotAccountStorage({
				reason: "delete-account",
				now,
			});
		}

		const snapshotNames = (await listAccountSnapshots()).map((entry) => entry.name);
		expect(snapshotNames.sort()).toEqual([
			"accounts-delete-account-snapshot-2026-03-13_00-00-00_000",
			"accounts-delete-account-snapshot-2026-03-12_00-00-00_000",
			"accounts-delete-account-snapshot-2026-03-11_00-00-00_000",
		].sort());
		expect(snapshotNames).not.toContain(manualBackup.name);
		expect(existsSync(manualBackup.path)).toBe(true);
	});

	it("retains rollback-referenced snapshots during snapshot retention", async () => {
		const now = Date.UTC(2026, 2, 16, 0, 0, 0, 0);
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "retention-refresh",
					accountId: "retention-account",
					addedAt: now,
					lastUsed: now,
				},
			],
		});

		const firstSnapshot = await snapshotAccountStorage({
			reason: "codex-cli-sync",
			now,
		});
		expect(firstSnapshot).not.toBeNull();
		if (!firstSnapshot) {
			throw new Error("expected first snapshot");
		}

		await appendSyncHistoryEntry({
			kind: "codex-cli-sync",
			recordedAt: now + 1,
			run: {
				outcome: "changed",
				runAt: now + 1,
				sourcePath: storagePath,
				targetPath: storagePath,
				summary: {
					sourceAccountCount: 1,
					targetAccountCountBefore: 1,
					targetAccountCountAfter: 1,
					addedAccountCount: 0,
					updatedAccountCount: 0,
					unchangedAccountCount: 1,
					destinationOnlyPreservedCount: 0,
					selectionChanged: false,
				},
				trigger: "manual",
				rollbackSnapshot: {
					name: firstSnapshot.name,
					path: firstSnapshot.path,
				},
			},
		});

		for (let index = 1; index <= 4; index += 1) {
			await snapshotAccountStorage({
				reason: "codex-cli-sync",
				now: now + index * 1_000,
			});
		}

		const keptNames = (await listAccountSnapshots()).map((entry) => entry.name).sort();
		const expectedKeptNames = [
			firstSnapshot.name,
			"accounts-codex-cli-sync-snapshot-2026-03-16_00-00-02_000",
			"accounts-codex-cli-sync-snapshot-2026-03-16_00-00-03_000",
			"accounts-codex-cli-sync-snapshot-2026-03-16_00-00-04_000",
		].sort();
		const expectedPrunedName =
			"accounts-codex-cli-sync-snapshot-2026-03-16_00-00-01_000";
		const backupsDir = getNamedBackupsDirectoryPath();

		expect(keptNames).toEqual(expectedKeptNames);
		for (const name of expectedKeptNames) {
			expect(existsSync(join(backupsDir, `${name}.json`))).toBe(true);
		}
		expect(existsSync(join(backupsDir, `${expectedPrunedName}.json`))).toBe(false);
	});

	it("retains rollback-referenced snapshots when history stores the target path with mixed separators", async () => {
		const now = Date.UTC(2026, 2, 16, 0, 30, 0, 0);
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "retention-separator-refresh",
					accountId: "retention-separator-account",
					addedAt: now,
					lastUsed: now,
				},
			],
		});

		const firstSnapshot = await snapshotAccountStorage({
			reason: "codex-cli-sync",
			now,
		});
		expect(firstSnapshot).not.toBeNull();
		if (!firstSnapshot) {
			throw new Error("expected first snapshot");
		}

		const recordedTargetPath = storagePath.includes("\\")
			? storagePath.replace(/\\/g, "/")
			: storagePath.replace(/\//g, "\\");

		await appendSyncHistoryEntry({
			kind: "codex-cli-sync",
			recordedAt: now + 1,
			run: {
				outcome: "changed",
				runAt: now + 1,
				sourcePath: storagePath,
				targetPath: recordedTargetPath,
				summary: {
					sourceAccountCount: 1,
					targetAccountCountBefore: 1,
					targetAccountCountAfter: 1,
					addedAccountCount: 0,
					updatedAccountCount: 0,
					unchangedAccountCount: 1,
					destinationOnlyPreservedCount: 0,
					selectionChanged: false,
				},
				trigger: "manual",
				rollbackSnapshot: {
					name: firstSnapshot.name,
					path: firstSnapshot.path,
				},
			},
		});

		for (let index = 1; index <= 4; index += 1) {
			await snapshotAccountStorage({
				reason: "codex-cli-sync",
				now: now + index * 1_000,
			});
		}

		const keptNames = (await listAccountSnapshots()).map((entry) => entry.name).sort();
		expect(keptNames).toContain(firstSnapshot.name);
		expect(existsSync(firstSnapshot.path)).toBe(true);
	});

	it("retains rollback-referenced snapshots when a newer manual sync has no checkpoint", async () => {
		const now = Date.UTC(2026, 2, 16, 1, 0, 0, 0);
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "retention-fallback-refresh",
					accountId: "retention-fallback-account",
					addedAt: now,
					lastUsed: now,
				},
			],
		});

		const firstSnapshot = await snapshotAccountStorage({
			reason: "codex-cli-sync",
			now,
		});
		expect(firstSnapshot).not.toBeNull();
		if (!firstSnapshot) {
			throw new Error("expected first snapshot");
		}

		const summary = {
			sourceAccountCount: 1,
			targetAccountCountBefore: 1,
			targetAccountCountAfter: 1,
			addedAccountCount: 0,
			updatedAccountCount: 0,
			unchangedAccountCount: 1,
			destinationOnlyPreservedCount: 0,
			selectionChanged: false,
		};

		await appendSyncHistoryEntry({
			kind: "codex-cli-sync",
			recordedAt: now + 1,
			run: {
				outcome: "changed",
				runAt: now + 1,
				sourcePath: storagePath,
				targetPath: storagePath,
				summary,
				trigger: "manual",
				rollbackSnapshot: {
					name: firstSnapshot.name,
					path: firstSnapshot.path,
				},
			},
		});

		for (let index = 1; index <= 4; index += 1) {
			await snapshotAccountStorage({
				reason: "codex-cli-sync",
				now: now + index * 1_000,
			});
		}

		await appendSyncHistoryEntry({
			kind: "codex-cli-sync",
			recordedAt: now + 10_000,
			run: {
				outcome: "changed",
				runAt: now + 10_000,
				sourcePath: storagePath,
				targetPath: storagePath,
				summary,
				trigger: "manual",
				rollbackSnapshot: null,
			},
		});

		const result = await pruneAutoGeneratedSnapshots();
		const backupsDir = getNamedBackupsDirectoryPath();
		const expectedKeptNames = [
			firstSnapshot.name,
			"accounts-codex-cli-sync-snapshot-2026-03-16_01-00-02_000",
			"accounts-codex-cli-sync-snapshot-2026-03-16_01-00-03_000",
			"accounts-codex-cli-sync-snapshot-2026-03-16_01-00-04_000",
		].sort();
		const expectedAlreadyPrunedNames = [
			"accounts-codex-cli-sync-snapshot-2026-03-16_01-00-01_000",
		];

		expect(result.kept.map((entry) => entry.name).sort()).toEqual(expectedKeptNames);
		expect(result.pruned).toEqual([]);
		for (const name of expectedKeptNames) {
			expect(existsSync(join(backupsDir, `${name}.json`))).toBe(true);
		}
		for (const name of expectedAlreadyPrunedNames) {
			expect(existsSync(join(backupsDir, `${name}.json`))).toBe(false);
		}
	});

	it("does not preserve rollback snapshot names that have no live snapshot path", async () => {
		const now = Date.UTC(2026, 2, 16, 1, 15, 0, 0);
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "retention-empty-path-refresh",
					accountId: "retention-empty-path-account",
					addedAt: now,
					lastUsed: now,
				},
			],
		});

		const firstSnapshot = await snapshotAccountStorage({
			reason: "codex-cli-sync",
			now,
		});
		expect(firstSnapshot).not.toBeNull();
		if (!firstSnapshot) {
			throw new Error("expected first snapshot");
		}

		await appendSyncHistoryEntry({
			kind: "codex-cli-sync",
			recordedAt: now + 1,
			run: {
				outcome: "changed",
				runAt: now + 1,
				sourcePath: storagePath,
				targetPath: storagePath,
				summary: {
					sourceAccountCount: 1,
					targetAccountCountBefore: 1,
					targetAccountCountAfter: 1,
					addedAccountCount: 0,
					updatedAccountCount: 0,
					unchangedAccountCount: 1,
					destinationOnlyPreservedCount: 0,
					selectionChanged: false,
				},
				trigger: "manual",
				rollbackSnapshot: {
					name: firstSnapshot.name,
					path: "   ",
				},
			},
		});

		for (let index = 1; index <= 4; index += 1) {
			await snapshotAccountStorage({
				reason: "codex-cli-sync",
				now: now + index * 1_000,
			});
		}

		const result = await pruneAutoGeneratedSnapshots();
		expect(result.kept.map((entry) => entry.name)).not.toContain(firstSnapshot.name);
		expect(existsSync(firstSnapshot.path)).toBe(false);
	});

	it("enforces snapshot retention against the transaction-pinned storage path", async () => {
		const primaryDir = join(workDir, "primary");
		const alternateDir = join(workDir, "alternate");
		const primaryStoragePath = join(primaryDir, "openai-codex-accounts.json");
		const alternateStoragePath = join(alternateDir, "openai-codex-accounts.json");
		await fs.mkdir(primaryDir, { recursive: true });
		await fs.mkdir(alternateDir, { recursive: true });
		setStoragePathDirect(primaryStoragePath);
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "tx-retention-refresh",
					accountId: "tx-retention-account",
					addedAt: 1,
					lastUsed: 1,
				},
			],
		});

		const baseTime = Date.UTC(2026, 2, 16, 3, 0, 0, 0);
		for (let index = 0; index < 3; index += 1) {
			await snapshotAccountStorage({
				reason: "codex-cli-sync",
				now: baseTime + index * 1_000,
			});
		}

		const primaryBackupsDir = getNamedBackupsDirectoryPath();
		await withAccountAndFlaggedStorageTransaction(async (current) => {
			setStoragePathDirect(alternateStoragePath);
			await snapshotAccountStorage({
				reason: "codex-cli-sync",
				now: baseTime + 3_000,
				storage: current,
			});
		});

		const primarySnapshotNames = (await fs.readdir(primaryBackupsDir))
			.filter((entry) => entry.endsWith(".json"))
			.map((entry) => entry.slice(0, -".json".length))
			.sort();
		const expectedPrimaryNames = [
			"accounts-codex-cli-sync-snapshot-2026-03-16_03-00-01_000",
			"accounts-codex-cli-sync-snapshot-2026-03-16_03-00-02_000",
			"accounts-codex-cli-sync-snapshot-2026-03-16_03-00-03_000",
		].sort();

		expect(primarySnapshotNames).toEqual(expectedPrimaryNames);
		expect(existsSync(primaryStoragePath)).toBe(true);
		expect(existsSync(alternateStoragePath)).toBe(false);
	});

	it("falls back to the newest live rollback snapshot when a newer recorded checkpoint file is missing", async () => {
		const now = Date.UTC(2026, 2, 16, 1, 30, 0, 0);
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "retention-live-refresh",
					accountId: "retention-live-account",
					addedAt: now,
					lastUsed: now,
				},
			],
		});

		const olderLiveSnapshot = await snapshotAccountStorage({
			reason: "codex-cli-sync",
			now,
		});
		expect(olderLiveSnapshot).not.toBeNull();
		if (!olderLiveSnapshot) {
			throw new Error("expected older live snapshot");
		}

		const newerMissingSnapshot = await snapshotAccountStorage({
			reason: "codex-cli-sync",
			now: now + 1_000,
		});
		expect(newerMissingSnapshot).not.toBeNull();
		if (!newerMissingSnapshot) {
			throw new Error("expected newer snapshot");
		}

		const summary = {
			sourceAccountCount: 1,
			targetAccountCountBefore: 1,
			targetAccountCountAfter: 1,
			addedAccountCount: 0,
			updatedAccountCount: 0,
			unchangedAccountCount: 1,
			destinationOnlyPreservedCount: 0,
			selectionChanged: false,
		};

		await appendSyncHistoryEntry({
			kind: "codex-cli-sync",
			recordedAt: now + 1,
			run: {
				outcome: "changed",
				runAt: now + 1,
				sourcePath: storagePath,
				targetPath: storagePath,
				summary,
				trigger: "manual",
				rollbackSnapshot: {
					name: olderLiveSnapshot.name,
					path: olderLiveSnapshot.path,
				},
			},
		});

		await appendSyncHistoryEntry({
			kind: "codex-cli-sync",
			recordedAt: now + 1_001,
			run: {
				outcome: "changed",
				runAt: now + 1_001,
				sourcePath: storagePath,
				targetPath: storagePath,
				summary,
				trigger: "manual",
				rollbackSnapshot: {
					name: newerMissingSnapshot.name,
					path: newerMissingSnapshot.path,
				},
			},
		});

		await fs.rm(newerMissingSnapshot.path, { force: true });
		expect(existsSync(newerMissingSnapshot.path)).toBe(false);

		for (let index = 2; index <= 4; index += 1) {
			await snapshotAccountStorage({
				reason: "codex-cli-sync",
				now: now + index * 1_000,
			});
		}

		const result = await pruneAutoGeneratedSnapshots();

		expect(result.pruned.map((entry) => entry.name)).not.toContain(
			olderLiveSnapshot.name,
		);
		expect(result.kept.map((entry) => entry.name)).toContain(
			olderLiveSnapshot.name,
		);
		expect(existsSync(olderLiveSnapshot.path)).toBe(true);
	});

	it("skips snapshot pruning when rollback history cannot be read", async () => {
		const now = Date.UTC(2026, 2, 16, 2, 0, 0, 0);
		await saveAccounts({
			version: 3,
			activeIndex: 0,
			accounts: [
				{
					refreshToken: "retention-read-error-refresh",
					accountId: "retention-read-error-account",
					addedAt: now,
					lastUsed: now,
				},
			],
		});

		const pinnedSnapshot = await snapshotAccountStorage({
			reason: "codex-cli-sync",
			now,
		});
		expect(pinnedSnapshot).not.toBeNull();
		if (!pinnedSnapshot) {
			throw new Error("expected pinned snapshot");
		}

		await appendSyncHistoryEntry({
			kind: "codex-cli-sync",
			recordedAt: now + 1,
			run: {
				outcome: "changed",
				runAt: now + 1,
				sourcePath: storagePath,
				targetPath: storagePath,
				summary: {
					sourceAccountCount: 1,
					targetAccountCountBefore: 1,
					targetAccountCountAfter: 1,
					addedAccountCount: 0,
					updatedAccountCount: 0,
					unchangedAccountCount: 1,
					destinationOnlyPreservedCount: 0,
					selectionChanged: false,
				},
				trigger: "manual",
				rollbackSnapshot: {
					name: pinnedSnapshot.name,
					path: pinnedSnapshot.path,
				},
			},
		});

		for (let index = 1; index <= 4; index += 1) {
			await snapshotAccountStorage({
				reason: "codex-cli-sync",
				now: now + index * 1_000,
			});
		}

		const currentSnapshots = await listAccountSnapshots();
		const retainedSnapshot = currentSnapshots.find(
			(entry) => entry.name !== pinnedSnapshot.name,
		);
		expect(retainedSnapshot).toBeDefined();
		if (!retainedSnapshot) {
			throw new Error("expected retained snapshot");
		}

		const readHistorySpy = vi
			.spyOn(syncHistoryModule, "readSyncHistory")
			.mockRejectedValueOnce(
				Object.assign(new Error("locked"), { code: "EPERM" }),
			);

		const result = await pruneAutoGeneratedSnapshots();

		expect(result.pruned).toEqual([]);
		expect(result.kept.map((entry) => entry.name)).toContain(pinnedSnapshot.name);
		expect(result.kept.map((entry) => entry.name)).toContain(retainedSnapshot.name);
		expect(existsSync(pinnedSnapshot.path)).toBe(true);
		expect(existsSync(retainedSnapshot.path)).toBe(true);
		readHistorySpy.mockRestore();
	});

	it("keeps auto snapshots when rollback history cannot be read", async () => {
		const backupsDir = getNamedBackupsDirectoryPath();
		await fs.mkdir(backupsDir, { recursive: true });

		const snapshotNames = [
			"accounts-delete-account-snapshot-2026-03-10_00-00-00_000",
			"accounts-delete-account-snapshot-2026-03-11_00-00-00_000",
			"accounts-delete-account-snapshot-2026-03-12_00-00-00_000",
			"accounts-delete-account-snapshot-2026-03-13_00-00-00_000",
		];
		const payload = JSON.stringify({
			version: 3,
			activeIndex: 0,
			accounts: [{ refreshToken: "rt-a" }],
		});
		for (const name of snapshotNames) {
			await fs.writeFile(join(backupsDir, `${name}.json`), payload, "utf-8");
		}

		const readSyncHistorySpy = vi
			.spyOn(syncHistoryModule, "readSyncHistory")
			.mockRejectedValueOnce(
				Object.assign(new Error("busy"), { code: "EPERM" }),
			);

		try {
			const result = await pruneAutoGeneratedSnapshots();
			expect(result.pruned).toEqual([]);
			expect(result.kept.map((entry) => entry.name).sort()).toEqual(
				snapshotNames.slice().sort(),
			);
			for (const name of snapshotNames) {
				expect(existsSync(join(backupsDir, `${name}.json`))).toBe(true);
			}
		} finally {
			readSyncHistorySpy.mockRestore();
		}
	});

	it("uses the production per-reason snapshot retention default", async () => {
		const payload = {
			version: 3,
			activeIndex: 0,
			accounts: [{ refreshToken: "rt-a" }],
		};
		const snapshotNames = [
			"accounts-codex-cli-sync-snapshot-2026-03-10_00-00-00_000",
			"accounts-codex-cli-sync-snapshot-2026-03-11_00-00-00_000",
			"accounts-codex-cli-sync-snapshot-2026-03-12_00-00-00_000",
			"accounts-codex-cli-sync-snapshot-2026-03-13_00-00-00_000",
		];
		await fs.mkdir(getNamedBackupsDirectoryPath(), { recursive: true });
		for (const name of snapshotNames) {
			await fs.writeFile(
				join(getNamedBackupsDirectoryPath(), `${name}.json`),
				JSON.stringify(payload),
				"utf-8",
			);
		}

		const result = await pruneAutoGeneratedSnapshots();

		expect(
			result.kept.map((entry) => entry.name).sort(),
		).toEqual(snapshotNames.slice(1).sort());
		expect(result.pruned.map((entry) => entry.name)).toEqual([snapshotNames[0]]);
	});
});

