//! cma-manager - foundation-owned module tree. Implementers: do NOT edit this file.
pub mod account_credentials;
pub mod account_pool_write;
pub mod action_panel;
pub mod flow;
pub mod manual_callback;
pub mod menu_actions;
pub mod menu_data;
pub mod oauth;
pub mod persist_selected;
