//! R5 drift guard for `config/schema/config.schema.json` (spec 01 §4.7,
//! ARCHITECTURE.md decision R5).
//!
//! The committed JSON schema stays a golden fixture generated by the TS tool
//! (`npm run generate:schema`). Rust does NOT re-implement the byte-exact
//! zod→JSON-schema generator; instead this module validates that the serde
//! `PluginConfig` model (field names, declaration ORDER, and per-field
//! bounds) matches the fixture, so schema drift in either direction fails a
//! test.
//!
//! The bound checks are black-box probes against
//! `cma_core::schemas::plugin_config::validate_field`: for each schema
//! property the declared type/enum/minimum/maximum is exercised with
//! accepting and rejecting values, proving the serde model enforces exactly
//! the committed constraints.

use std::path::{Path, PathBuf};

use serde_json::{Map, Value, json};

use cma_core::json_io::{ReadJsonError, read_json_file};
use cma_core::schemas::plugin_config::{PLUGIN_CONFIG_KEYS, validate_field};

/// Repo-relative path of the committed, generated schema file (mirrors the TS
/// `CONFIG_SCHEMA_RELATIVE_PATH`).
pub const CONFIG_SCHEMA_RELATIVE_PATH: &str = "config/schema/config.schema.json";

/// Absolute path of the committed fixture, anchored at the workspace root
/// (`crates/config/../..`).
pub fn committed_config_schema_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join(CONFIG_SCHEMA_RELATIVE_PATH)
}

/// Load and parse the committed schema fixture.
pub fn load_committed_config_schema() -> Result<Value, ReadJsonError> {
    read_json_file(&committed_config_schema_path())
}

fn push_issue(issues: &mut Vec<String>, message: impl Into<String>) {
    issues.push(message.into());
}

fn probe_accepts(key: &str, value: &Value) -> bool {
    validate_field(key, value).is_some()
}

/// Check one schema property definition against the serde model's per-field
/// validator.
fn check_property(key: &str, definition: &Map<String, Value>, issues: &mut Vec<String>) {
    // The chain field has a bespoke record shape.
    if key == "unsupportedCodexFallbackChain" {
        if definition.get("type").and_then(Value::as_str) != Some("object") {
            push_issue(issues, format!("{key}: fixture type is not \"object\""));
        }
        let min_length = definition
            .get("additionalProperties")
            .and_then(|ap| ap.get("items"))
            .and_then(|items| items.get("minLength"))
            .and_then(Value::as_i64);
        if min_length != Some(1) {
            push_issue(
                issues,
                format!("{key}: fixture no longer requires non-empty chain targets"),
            );
        }
        for (probe, should_accept) in [
            (json!({ "a": ["b"] }), true),
            (json!({}), true),
            (json!({ "a": [""] }), false),
            (json!({ "a": "b" }), false),
            (json!(["a"]), false),
            (json!("x"), false),
        ] {
            if probe_accepts(key, &probe) != should_accept {
                push_issue(
                    issues,
                    format!(
                        "{key}: serde model {} {probe} but the fixture says it should {}",
                        if should_accept { "rejects" } else { "accepts" },
                        if should_accept { "be accepted" } else { "be rejected" },
                    ),
                );
            }
        }
        return;
    }

    if let Some(options) = definition.get("enum").and_then(Value::as_array) {
        // Enum property: every fixture option accepted; foreign values and
        // non-strings rejected.
        if definition.get("type").and_then(Value::as_str) != Some("string") {
            push_issue(issues, format!("{key}: fixture enum is not string-typed"));
        }
        for option in options {
            if !probe_accepts(key, option) {
                push_issue(
                    issues,
                    format!("{key}: serde model rejects fixture enum option {option}"),
                );
            }
        }
        if probe_accepts(key, &json!("__drift_probe__")) {
            push_issue(
                issues,
                format!("{key}: serde model accepts values outside the fixture enum"),
            );
        }
        if probe_accepts(key, &json!(0)) {
            push_issue(issues, format!("{key}: serde model accepts non-strings"));
        }
        return;
    }

    match definition.get("type").and_then(Value::as_str) {
        Some("boolean") => {
            if !probe_accepts(key, &json!(true)) || !probe_accepts(key, &json!(false)) {
                push_issue(issues, format!("{key}: serde model rejects booleans"));
            }
            if probe_accepts(key, &json!(1)) || probe_accepts(key, &json!("true")) {
                push_issue(
                    issues,
                    format!("{key}: serde model accepts non-boolean values"),
                );
            }
        }
        Some("number") => {
            let minimum = definition.get("minimum").and_then(Value::as_f64);
            let maximum = definition.get("maximum").and_then(Value::as_f64);
            let Some(minimum) = minimum else {
                push_issue(
                    issues,
                    format!("{key}: fixture numeric property lost its minimum"),
                );
                return;
            };
            if !probe_accepts(key, &json!(minimum)) {
                push_issue(
                    issues,
                    format!("{key}: serde model rejects the fixture minimum {minimum}"),
                );
            }
            if probe_accepts(key, &json!(minimum - 1.0)) {
                push_issue(
                    issues,
                    format!("{key}: serde model accepts values below the fixture minimum {minimum}"),
                );
            }
            match maximum {
                Some(maximum) => {
                    if !probe_accepts(key, &json!(maximum)) {
                        push_issue(
                            issues,
                            format!("{key}: serde model rejects the fixture maximum {maximum}"),
                        );
                    }
                    if probe_accepts(key, &json!(maximum + 1.0)) {
                        push_issue(
                            issues,
                            format!(
                                "{key}: serde model accepts values above the fixture maximum {maximum}"
                            ),
                        );
                    }
                }
                None => {
                    if !probe_accepts(key, &json!(minimum + 1.0e15)) {
                        push_issue(
                            issues,
                            format!("{key}: serde model enforces a maximum the fixture lacks"),
                        );
                    }
                }
            }
            if probe_accepts(key, &json!("123")) {
                push_issue(issues, format!("{key}: serde model accepts numeric strings"));
            }
        }
        other => push_issue(
            issues,
            format!("{key}: unexpected fixture property type {other:?}"),
        ),
    }
}

/// Compare the committed schema against the serde `PluginConfig` model.
/// Returns a list of human-readable drift findings; empty = no drift.
pub fn plugin_config_schema_drift(schema: &Value) -> Vec<String> {
    let mut issues = Vec::new();

    let Some(properties) = schema
        .get("$defs")
        .and_then(|defs| defs.get("pluginConfig"))
        .and_then(|def| def.get("properties"))
        .and_then(Value::as_object)
    else {
        return vec!["$defs.pluginConfig.properties missing from the committed schema".to_string()];
    };

    // Field NAMES and ORDER must match the serde declaration order exactly
    // (zod shape order == serde struct order).
    let fixture_keys: Vec<&str> = properties.keys().map(String::as_str).collect();
    let model_keys: Vec<&str> = PLUGIN_CONFIG_KEYS.to_vec();
    if fixture_keys != model_keys {
        push_issue(
            &mut issues,
            format!(
                "property name/order drift: fixture {fixture_keys:?} vs serde model {model_keys:?}"
            ),
        );
    }

    for (key, definition) in properties {
        let Some(definition) = definition.as_object() else {
            push_issue(&mut issues, format!("{key}: property definition is not an object"));
            continue;
        };
        check_property(key, definition, &mut issues);
    }

    // Root skeleton sanity: the runtime tolerates unknown keys, so the
    // generated definition must NOT emit additionalProperties:false
    // (zod io:"input" semantics — spec 01 §4.7).
    if let Some(plugin_config_def) = schema.get("$defs").and_then(|d| d.get("pluginConfig"))
        && plugin_config_def.get("additionalProperties") == Some(&Value::Bool(false))
    {
        push_issue(
            &mut issues,
            "pluginConfig definition emits additionalProperties:false (io:\"input\" drift)",
        );
    }

    issues
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn committed_schema_matches_the_serde_model() {
        let schema = load_committed_config_schema()
            .unwrap_or_else(|error| panic!("failed to read {CONFIG_SCHEMA_RELATIVE_PATH}: {error}"));
        let drift = plugin_config_schema_drift(&schema);
        assert!(
            drift.is_empty(),
            "config schema drift detected:\n{}",
            drift.join("\n")
        );
    }

    #[test]
    fn committed_schema_root_skeleton_is_intact() {
        let schema = load_committed_config_schema().expect("fixture readable");
        assert_eq!(
            schema.get("$schema").and_then(Value::as_str),
            Some("https://json-schema.org/draft/2020-12/schema")
        );
        assert_eq!(
            schema.get("$id").and_then(Value::as_str),
            Some("https://codex-multi-auth.local/schema/config.schema.json")
        );
        assert_eq!(
            schema.get("title").and_then(Value::as_str),
            Some("codex-multi-auth config template")
        );
        assert_eq!(
            schema.get("required"),
            Some(&serde_json::json!(["plugin", "provider"]))
        );
        assert_eq!(schema.get("additionalProperties"), Some(&Value::Bool(true)));
        assert_eq!(
            schema
                .get("properties")
                .and_then(|p| p.get("pluginConfig"))
                .and_then(|p| p.get("$ref"))
                .and_then(Value::as_str),
            Some("#/$defs/pluginConfig")
        );
    }

    #[test]
    fn drift_detector_flags_a_tampered_schema() {
        let schema = load_committed_config_schema().expect("fixture readable");

        // Removing a property must be reported.
        let mut missing = schema.clone();
        missing["$defs"]["pluginConfig"]["properties"]
            .as_object_mut()
            .unwrap()
            .shift_remove("codexMode");
        assert!(!plugin_config_schema_drift(&missing).is_empty());

        // Changing a bound must be reported.
        let mut wrong_bound = schema.clone();
        wrong_bound["$defs"]["pluginConfig"]["properties"]["toastDurationMs"]["minimum"] =
            serde_json::json!(500);
        assert!(!plugin_config_schema_drift(&wrong_bound).is_empty());

        // Changing an enum must be reported.
        let mut wrong_enum = schema;
        wrong_enum["$defs"]["pluginConfig"]["properties"]["routingMutex"]["enum"] =
            serde_json::json!(["enabled", "legacy", "extra"]);
        assert!(!plugin_config_schema_drift(&wrong_enum).is_empty());
    }
}
