//! cma-accounts - foundation-owned module tree. Implementers: do NOT edit this file.
pub mod account_policy;
pub mod capability_matrix;
pub mod capability_policy;
pub mod entitlement_cache;
pub mod manager;
pub mod manager_persistence;
pub mod manager_selection;
pub mod rate_limits;
pub mod routing_profiles;
pub mod session_affinity;
