//! cma-manager - foundation-owned module tree. Implementers: do NOT edit this file.
pub mod backend;
pub mod dashboard;
pub mod experimental;
pub mod hub;
pub mod panels;
pub mod persist;
pub mod preview;
pub mod schema;
pub mod write_queue;
