//! cma-manager - foundation-owned module tree. Implementers: do NOT edit this file.
pub mod commands;
pub mod dispatcher;
pub mod forecast_report_shared;
pub mod formatters;
pub mod health_check;
pub mod help;
pub mod integration_generators;
pub mod login;
pub mod oc_chatgpt;
pub mod quota_cache_helpers;
pub mod rate_limit_markers;
pub mod registry;
pub mod repair;
pub mod settings;
pub mod update_notice;
